version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: yarn run start:dev --debug 0.0.0.0:9229
    ports:
      - ${PORT:-3000}:${PORT:-3000}
      - 9228:9229
    env_file:
      - ./.env
    volumes:
      - ./src:/app/src
      - ./migration:/app/migration
      - ./dist:/app/dist
      - ./swagger.json:/app/swagger.json
    depends_on:
      - db

  db:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
    volumes:
      - .docker/volumes/mariadb/data:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin:5
    ports:
      - 8080:80
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    links:
      - db:db
    depends_on:
      - db